// LocalizationService.swift
// Memoria for iPhone - In-Code Localization Service
// Phase 3: Japanese / English / Spanish

import SwiftUI
import Combine

// MARK: - AppLanguage

enum AppLanguage: String, CaseIterable, Identifiable {
    case japanese = "ja"
    case english = "en"
    case spanish = "es"

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .japanese: return "日本語"
        case .english: return "English"
        case .spanish: return "Español"
        }
    }
}

// MARK: - LocalizationService

@MainActor
class LocalizationService: ObservableObject {
    static let shared = LocalizationService()

    @Published var currentLanguage: AppLanguage {
        didSet {
            UserDefaults.standard.set(currentLanguage.rawValue, forKey: Self.languageKey)
        }
    }

    private static let languageKey = "appLanguage"

    private init() {
        let savedRaw = UserDefaults.standard.string(forKey: Self.languageKey) ?? AppLanguage.japanese.rawValue
        self.currentLanguage = AppLanguage(rawValue: savedRaw) ?? .japanese
    }

    /// Look up a localized string by key. Returns the key itself if no translation is found.
    func localized(_ key: String) -> String {
        translations[currentLanguage]?[key] ?? key
    }

    /// Convenience subscript
    subscript(_ key: String) -> String { localized(key) }

    // MARK: - Translation Dictionary

    private let translations: [AppLanguage: [String: String]] = [
        .japanese: [
            // General / shared
            "done": "完了",
            "cancel": "キャンセル",
            "delete": "削除",
            "save": "保存",
            "close": "閉じる",
            "retry": "再試行",
            "back": "戻る",
            "next": "次へ",
            "in_use": "使用中",
            "rename_session": "名前を変更",
            "rename_session_title": "セッション名を変更",
            "rename_session_msg": "新しいタイトルを入力してください",
            "session_title_placeholder": "セッション名",
            "state_generating": "生成中",
            "state_loading": "ロード中",
            "state_idle": "待機中",
            "state_not_loaded": "未ロード",
            "offline": "オフライン",
            "settings": "設定",
            "app_name": "Memoria",
            "reload": "再読込",

            // ContentView / ModelLoadingView / ErrorView
            "model_loading": "モデルを読み込み中...",
            "first_download_wifi": "初回はWi-Fiでのダウンロードが必要です\n（約600MB）",
            "error_occurred": "エラーが発生しました",

            // SessionListView
            "welcome_heading": "Memoria へようこそ",
            "welcome_sub": "あなたとの会話を記憶する\nオフラインAIアシスタント",
            "feature_offline": "完全オフライン — データは端末内",
            "feature_memory": "会話を記憶して成長するAI",
            "feature_multilang": "日本語・英語・スペイン語対応",
            "new_conversation": "新しい会話",
            "search_sessions": "セッションを検索...",
            "just_now": "たった今",
            "yesterday": "昨日",
            "min_ago_fmt": "%d分前",
            "hour_ago_fmt": "%d時間前",
            "days_ago_fmt": "%d日前",

            // ChatView
            "placeholder_message": "メッセージを入力...",
            "placeholder_command": "/ でコマンドを呼び出せます",
            "placeholder_ask": "何でも聞いてください",
            "chat_start": "会話を始めましょう",
            "chat_empty_sub": "完全オフラインで動作します\n/ でコマンドも使えます",
            "cmd_help_desc": "コマンド一覧",
            "cmd_english_desc": "英語ネイティブに変換",
            "cmd_japanese_desc": "日本語ネイティブに変換",
            "cmd_spanish_desc": "西語ネイティブに変換",
            "cmd_cal_desc": "言語判定して校正",
            "cmd_grammar_desc": "翻訳・代替表現・文法解説",
            "cmd_remember_desc": "記憶に保存",
            "cmd_memory_desc": "記憶一覧",
            "cmd_clear_desc": "新しい会話",
            "voice_permission_title": "音声入力の許可が必要です",
            "voice_permission_msg": "音声入力を使用するには、マイクと音声認識へのアクセスを許可してください。",
            "open_settings": "設定を開く",

            // SettingsView
            "section_appearance": "外観",
            "section_model": "モデル",
            "section_memory": "記憶",
            "section_commands": "カスタムコマンド",
            "section_language": "言語",
            "section_about": "アプリ情報",
            "follow_system_theme": "システムテーマに従う",
            "theme_label": "テーマ",
            "color_palette": "カラーパレット",
            "model_label": "モデル",
            "memory_usage": "メモリ使用量",
            "change_model": "モデルを変更",
            "global_memory_label": "グローバルメモリ",
            "session_count_label": "セッション数",
            "clear_global_memory": "グローバルメモリを全削除",

            // UserCommandManagementView
            "cmd_manage_title": "カスタムコマンド",
            "cmd_manage_empty": "コマンドがまだありません",
            "cmd_manage_empty_sub": "右上の ＋ ボタンで追加できます",
            "cmd_add_title": "コマンドを追加",
            "cmd_field_name": "コマンド名（例: summarize）",
            "cmd_field_desc": "説明（例: テキストを要約する）",
            "cmd_field_template": "プロンプトテンプレート",
            "cmd_template_hint": "{input} の部分がコマンド後のテキストに置き換わります\n例: 以下を3行で要約してください: {input}",
            "cmd_name_label": "名前",
            "cmd_desc_label": "説明",
            "cmd_template_label": "テンプレート",
            "cmd_usage_label": "使い方",
            "cmd_usage_example": "/コマンド名 [送りたいテキスト]",
            "cmd_delete_confirm": "このコマンドを削除しますか？",
            "cmd_settings_row": "カスタムコマンドを管理",
            "cmd_settings_sub": "チャットで使える独自コマンドを追加・削除",
            "cmd_count_fmt": "%d 個",
            "cmd_name_invalid": "コマンド名に使えない文字が含まれています",
            "cmd_name_duplicate": "同じ名前のコマンドが既に存在します",
            "cmd_add_success": "コマンドを追加しました",
            "cmd_edit_title": "コマンドを編集",
            "cmd_name_readonly": "変更不可",
            // GlobalMemoryManagementView
            "mem_manage_title": "グローバルメモリ",
            "mem_empty_title": "メモリが空です",
            "mem_empty_sub": "/remember コマンドで記憶を追加できます",
            "mem_add_title": "メモリを追加",
            "mem_add_placeholder": "覚えておきたい内容を入力",
            "mem_add_msg": "チャット全体で参照される記憶として保存されます",
            "mem_delete_confirm": "このメモリを削除しますか？",
            "mem_count_fmt": "%d 件の記憶",
            "mem_count_unit": "件",
            "mem_hint": "左スワイプで削除",
            "mem_source_manual": "手動",
            "mem_source_auto": "自動",
            "delete_memory_title": "グローバルメモリを全削除",
            "delete_memory_msg": "すべてのグローバルメモリが削除されます。この操作は取り消せません。",
            "app_language": "アプリの言語",
            "version_label": "バージョン",
            "inference_engine": "推論エンジン",
            "fully_offline_label": "完全オフライン対応",
            "disclaimer_label": "免責事項",
            "disclaimer_nav_title": "免責事項",
            "disclaimer_ai_title": "AIの回答精度について",
            "disclaimer_ai_body": "Memoriaが生成する回答はAIモデルによる推測です。内容の正確性・完全性・適時性を一切保証しません。医療・法律・財務等の重要な判断には専門家へご相談ください。AIの回答を参考にした結果生じたいかなる損害についても開発者は責任を負いません。",
            "disclaimer_model_title": "使用AIモデルの帰属",
            "disclaimer_model_body": "本アプリはGoogle DeepMindが開発したGemma（オープンウェイトモデル）を使用しています。GemmaはGoogle Gemma利用規約のもとで提供されています。モデルのダウンロードにはHuggingFaceの利用規約への同意が必要です。",
            "disclaimer_privacy_title": "プライバシー",
            "disclaimer_privacy_body": "会話データ・AIの記憶はすべてお使いのiPhone内にのみ保存されます。マイクは音声入力にのみ使用し、音声データは変換後即時廃棄されます。外部サーバーへのデータ送信は行いません（AIモデルの初回ダウンロードを除く）。",
            "disclaimer_oss_title": "オープンソースライセンス",
            "disclaimer_oss_body": "本アプリはLLM.swift（MIT）、GRDB.swift（MIT）、llama.cpp（MIT）、Catppuccin（MIT）を使用しています。各ライブラリの著作権はそれぞれの作者に帰属します。",
            "last_updated": "最終更新: 2026年4月",

            // ModelManagementView
            "model_mgmt_title": "モデル管理",
            "local_models": "ローカルモデル",
            "local_models_sub": "オフライン動作・プライバシー保護",
            "cloud_models": "クラウドモデル",
            "cloud_models_sub": "高性能・要インターネット接続",
            "unload_btn": "使用解除",
            "switch_btn": "切り替え",
            "download_btn": "ダウンロード",
            "use_model": "使用する",
            "badge_beta": "β 実験的",
            "web_search_badge": "Web検索対応",
            "web_search_banner_title": "Web検索機能について",
            "web_search_banner_body": "クラウドAIがWeb情報を必要と判断した際、自動でインターネット検索を実行します。OpenAIモデルは現在Web検索非対応です。",
            "downloading": "ダウンロード中...",
            "switching": "切替中...",
            "key_required": "要設定",
            "use_btn": "使用",
            "api_key_not_set": "APIキー未設定",
            "api_key_change": "変更",
            "api_key_setup": "設定",
            "unload_confirm_title": "モデルの使用を解除しますか？",
            "unload_confirm_msg": "メモリからモデルを解放します。次回使用時に再ロードが必要です。",
            "unload_confirm_action": "使用解除する",
            "current_model_header": "現在のモデル",
            "not_selected": "未選択",
            "offline_warning_title": "オフライン",
            "offline_warning_sub": "クラウドモデルにはインターネット接続が必要です",
            "info_wifi": "ローカルモデルは初回のみWi-Fiでダウンロードが必要です",
            "info_keychain": "APIキーはiPhone内のKeychainに暗号化保存されます",
            "device_memory": "このデバイスのメモリ: %@ GB",
            "mem_optimal": "推奨",
            "mem_usable": "動作可",
            "mem_tight": "注意",
            "mem_tight_warning": "メモリ不足で不安定になる可能性があります。動作はしますが自己責任でご利用ください。",

            // QuickModelPickerView
            "quick_model_title": "モデルを切り替え",
            "current_model_active": "現在使用中のモデル",
            "local_models_short_sub": "オフライン・プライバシー保護",
            "api_key_set": "APIキー設定済み",
            "setup_api_key": "設定する",
            "api_key_needed": "APIキー必要",
            "full_settings_label": "詳細なモデル設定・APIキー管理",
            "full_settings_sub": "モデルのダウンロードやAPIキーの設定はこちら",

            // ChatView UX improvements
            "new_session_confirm_title": "新しい会話を始めますか？",
            "new_session_confirm_msg": "現在の会話は保存されます",
            "new_session_confirm_btn": "新しい会話を始める",
            "api_key_required_title": "APIキーが必要です",
            "api_key_required_msg": "このモデルを使用するにはAPIキーの設定が必要です。今すぐ設定しますか？",
            "api_key_set_now": "今すぐ設定",
            "recording_label": "録音中...",
            "tap_to_stop": "タップで停止",
            "swipe_hint": "← スワイプで削除・名前変更",
            "offline_cloud_banner": "オフライン中 — クラウドAIは利用できません",
            "badge_local": "ローカル",
            "badge_cloud": "クラウド",
            "api_key_setup_nav_title": "APIキー設定",
            "api_key_keychain_note": "APIキーはiPhone内のKeychainに暗号化して保存されます",
            "api_key_already_set": "設定済み",

            // OnboardingView
            "onboarding_welcome": "Memoriaへようこそ",
            "onboarding_subtitle": "あなたとの会話を記憶する\nプライベートAIアシスタント",
            "badge_offline": "完全オフライン",
            "badge_memory": "記憶機能",
            "badge_voice": "音声入力",
            "features_title": "Memoriaの特徴",
            "onb_feature1_title": "iPhoneの中だけで動作",
            "onb_feature1_desc": "AIの処理はすべてiPhone内で完結。データがデバイスの外に出ることはありません。",
            "onb_feature2_title": "会話を記憶する",
            "onb_feature2_desc": "セッションをまたいで会話内容を要約・記憶。文脈を持ったパーソナルアシスタントです。",
            "onb_feature3_title": "Powered by Gemma (Google DeepMind)",
            "onb_feature3_desc": "最新のオープンソースLLMを使用。iPhone 16以降ではより高性能なGemma 4も利用可能です。",
            "onb_disclaimer_title": "ご利用前にお読みください",
            "onb_disclaimer1_title": "⚠️ AIの回答精度について",
            "onb_disclaimer1_body": "Memoriaが生成する回答は、AIモデルが推測したものです。内容の正確性・完全性・適時性を一切保証しません。重要な判断（医療・法律・財務等）には専門家にご相談ください。AIの回答を参考にした結果生じたいかなる損害についても、開発者は責任を負いません。",
            "onb_disclaimer2_title": "🤖 使用AIモデルについて",
            "onb_disclaimer2_body": "本アプリはGoogle DeepMindが開発したGemma（オープンモデル）をローカル実行します。モデルはHuggingFaceよりダウンロードされます。利用にはGoogle Gemma利用規約への同意が必要です。",
            "onb_disclaimer3_title": "🔒 プライバシーについて",
            "onb_disclaimer3_body": "会話データはiPhone内にのみ保存されます。マイクは音声入力にのみ使用し、録音データは一切保存・送信しません。",
            "onb_agreement": "上記の免責事項を読み、理解した上で自己責任においてMemoriaを利用することに同意します。",
            "onb_agree_btn": "同意してMemoriaを始める",
        ],
        .english: [
            // General / shared
            "done": "Done",
            "cancel": "Cancel",
            "delete": "Delete",
            "save": "Save",
            "close": "Close",
            "retry": "Retry",
            "back": "Back",
            "next": "Next",
            "in_use": "In use",
            "rename_session": "Rename",
            "rename_session_title": "Rename Session",
            "rename_session_msg": "Enter a new title for this session",
            "session_title_placeholder": "Session title",
            "state_generating": "Generating",
            "state_loading": "Loading",
            "state_idle": "Ready",
            "state_not_loaded": "Not loaded",
            "offline": "Offline",
            "settings": "Settings",
            "app_name": "Memoria",
            "reload": "Reload",

            // ContentView / ModelLoadingView / ErrorView
            "model_loading": "Loading model...",
            "first_download_wifi": "First-time download requires Wi-Fi\n(~600MB)",
            "error_occurred": "An error occurred",

            // SessionListView
            "welcome_heading": "Welcome to Memoria",
            "welcome_sub": "Your offline AI assistant\nthat remembers you",
            "feature_offline": "Fully offline — data stays on device",
            "feature_memory": "AI that learns from your conversations",
            "feature_multilang": "Japanese, English & Spanish",
            "new_conversation": "New Conversation",
            "search_sessions": "Search sessions...",
            "just_now": "just now",
            "yesterday": "Yesterday",
            "min_ago_fmt": "%d min ago",
            "hour_ago_fmt": "%d h ago",
            "days_ago_fmt": "%d days ago",

            // ChatView
            "placeholder_message": "Type a message...",
            "placeholder_command": "Type / for commands",
            "placeholder_ask": "Ask me anything",
            "chat_start": "Start a conversation",
            "chat_empty_sub": "Works fully offline\nType / to use commands",
            "cmd_help_desc": "List commands",
            "cmd_english_desc": "Native English",
            "cmd_japanese_desc": "Native Japanese",
            "cmd_spanish_desc": "Native Spanish",
            "cmd_cal_desc": "Auto-detect & proofread",
            "cmd_grammar_desc": "Translate & grammar",
            "cmd_remember_desc": "Save to memory",
            "cmd_memory_desc": "Show memories",
            "cmd_clear_desc": "New conversation",
            "voice_permission_title": "Microphone permission required",
            "voice_permission_msg": "Please allow microphone and speech recognition access to use voice input.",
            "open_settings": "Open Settings",

            // SettingsView
            "section_appearance": "Appearance",
            "section_model": "Model",
            "section_memory": "Memory",
            "section_commands": "Custom Commands",
            "section_language": "Language",
            "section_about": "About",
            "follow_system_theme": "Follow system theme",
            "theme_label": "Theme",
            "color_palette": "Color palette",
            "model_label": "Model",
            "memory_usage": "Memory usage",
            "change_model": "Change Model",
            "global_memory_label": "Global Memory",
            "session_count_label": "Sessions",
            "clear_global_memory": "Clear all global memory",
            "delete_memory_title": "Clear all global memory",
            "delete_memory_msg": "All global memory will be deleted. This action cannot be undone.",
            "app_language": "App Language",
            "version_label": "Version",
            "inference_engine": "Inference engine",
            "fully_offline_label": "Fully offline capable",
            "disclaimer_label": "Disclaimer",
            "disclaimer_nav_title": "Disclaimer",
            "disclaimer_ai_title": "About AI accuracy",
            "disclaimer_ai_body": "Responses generated by Memoria are AI model inferences. We make no warranty as to accuracy, completeness, or timeliness. For important decisions (medical, legal, financial), consult a professional. The developer is not liable for any damages resulting from reliance on AI responses.",
            "disclaimer_model_title": "AI model attribution",
            "disclaimer_model_body": "This app uses Gemma, an open-weight model developed by Google DeepMind, under the Google Gemma Terms of Use. Downloading the model requires agreement to HuggingFace's Terms of Service.",
            "disclaimer_privacy_title": "Privacy",
            "disclaimer_privacy_body": "All conversation data and AI memories are stored solely on your iPhone. The microphone is used only for voice input, and audio data is discarded immediately after transcription. No data is sent to external servers (except the initial AI model download).",
            "disclaimer_oss_title": "Open source licenses",
            "disclaimer_oss_body": "This app uses LLM.swift (MIT), GRDB.swift (MIT), llama.cpp (MIT), and Catppuccin (MIT). Copyright belongs to their respective authors.",
            "last_updated": "Last updated: April 2026",

            // ModelManagementView
            "model_mgmt_title": "Model Management",
            "local_models": "Local Models",
            "local_models_sub": "Offline · Privacy protected",
            "cloud_models": "Cloud Models",
            "cloud_models_sub": "High performance · Requires internet",
            "unload_btn": "Release",
            "switch_btn": "Switch",
            "download_btn": "Download",
            "use_model": "Use",
            "badge_beta": "β Beta",
            "web_search_badge": "Web Search",
            "web_search_banner_title": "About Web Search",
            "web_search_banner_body": "Cloud AI will automatically search the internet when it needs up-to-date information. OpenAI models do not support web search currently.",
            "downloading": "Downloading...",
            "switching": "Switching...",
            "key_required": "Key needed",
            "use_btn": "Use",
            "api_key_not_set": "API key not set",
            "api_key_change": "Change",
            "api_key_setup": "Set up",
            "unload_confirm_title": "Release model from memory?",
            "unload_confirm_msg": "The model will be released from memory. It will reload next time.",
            "unload_confirm_action": "Release",
            "current_model_header": "Current Model",
            "not_selected": "Not selected",
            "offline_warning_title": "Offline",
            "offline_warning_sub": "Cloud models require an internet connection",
            "info_wifi": "Local models require a one-time Wi-Fi download",
            "info_keychain": "API keys are encrypted and stored in iPhone Keychain",
            "device_memory": "Device memory: %@ GB",
            "mem_optimal": "Recommended",
            "mem_usable": "Usable",
            "mem_tight": "Caution",
            "mem_tight_warning": "May become unstable due to low memory. Runs, but use at your own risk.",

            // QuickModelPickerView
            "quick_model_title": "Switch Model",
            "current_model_active": "Currently active model",
            "local_models_short_sub": "Offline · Privacy protected",
            "api_key_set": "API key configured",
            "setup_api_key": "Set up",
            "api_key_needed": "API key needed",
            "full_settings_label": "Advanced model settings & API keys",
            "full_settings_sub": "Download models and manage API keys",

            // ChatView UX improvements
            "new_session_confirm_title": "Start a new conversation?",
            "new_session_confirm_msg": "Your current conversation will be saved",
            "new_session_confirm_btn": "Start new conversation",
            "api_key_required_title": "API Key Required",
            "api_key_required_msg": "An API key is needed to use this model. Set it up now?",
            "api_key_set_now": "Set up now",
            "recording_label": "Listening...",
            "tap_to_stop": "Tap to stop",
            "swipe_hint": "← Swipe to delete or rename",
            "offline_cloud_banner": "Offline — Cloud AI unavailable",
            "badge_local": "Local",
            "badge_cloud": "Cloud",
            "api_key_setup_nav_title": "API Key Setup",
            "api_key_keychain_note": "Your API key is encrypted and stored in iPhone Keychain",
            "api_key_already_set": "Configured",

            // OnboardingView
            "onboarding_welcome": "Welcome to Memoria",
            "onboarding_subtitle": "A private AI assistant\nthat remembers you",
            "badge_offline": "Fully offline",
            "badge_memory": "Memory",
            "badge_voice": "Voice input",
            "features_title": "Features",
            "onb_feature1_title": "Runs entirely on iPhone",
            "onb_feature1_desc": "All AI processing happens on-device. Your data never leaves your iPhone.",
            "onb_feature2_title": "Remembers conversations",
            "onb_feature2_desc": "Summarizes and remembers conversations across sessions. A personal assistant with context.",
            "onb_feature3_title": "Powered by Gemma (Google DeepMind)",
            "onb_feature3_desc": "Uses the latest open-source LLMs. Gemma 4 available on iPhone 16 and later.",
            "onb_disclaimer_title": "Before you begin",
            "onb_disclaimer1_title": "⚠️ About AI accuracy",
            "onb_disclaimer1_body": "Responses generated by Memoria are AI model inferences. We make no warranty as to accuracy, completeness, or timeliness. For critical decisions (medical, legal, financial), consult a professional. The developer is not liable for any damages resulting from reliance on AI responses.",
            "onb_disclaimer2_title": "🤖 About the AI model",
            "onb_disclaimer2_body": "This app runs Gemma (an open model by Google DeepMind) locally. The model is downloaded from HuggingFace. Use requires acceptance of the Google Gemma Terms of Use.",
            "onb_disclaimer3_title": "🔒 Privacy",
            "onb_disclaimer3_body": "Conversation data is stored solely on your iPhone. The microphone is used only for voice input; no recordings are saved or transmitted.",
            "onb_agreement": "I have read and understood the above disclaimers and agree to use Memoria at my own risk.",
            "onb_agree_btn": "Agree and start Memoria",

            // UserCommandManagementView
            "cmd_manage_title": "Custom Commands",
            "cmd_manage_empty": "No commands yet",
            "cmd_manage_empty_sub": "Tap + to add your first command",
            "cmd_add_title": "Add Command",
            "cmd_field_name": "Command name (e.g. summarize)",
            "cmd_field_desc": "Description (e.g. Summarize text)",
            "cmd_field_template": "Prompt template",
            "cmd_template_hint": "{input} will be replaced by the text after the command\nExample: Summarize the following in 3 lines: {input}",
            "cmd_name_label": "Name",
            "cmd_desc_label": "Description",
            "cmd_template_label": "Template",
            "cmd_usage_label": "How to use",
            "cmd_usage_example": "/commandname [text to send]",
            "cmd_delete_confirm": "Delete this command?",
            "cmd_settings_row": "Manage Custom Commands",
            "cmd_settings_sub": "Add and remove your own chat commands",
            "cmd_count_fmt": "%d commands",
            "cmd_name_invalid": "Command name contains invalid characters",
            "cmd_name_duplicate": "A command with that name already exists",
            "cmd_add_success": "Command added",
            "cmd_edit_title": "Edit Command",
            "cmd_name_readonly": "Read-only",
            // GlobalMemoryManagementView
            "mem_manage_title": "Global Memory",
            "mem_empty_title": "Memory is empty",
            "mem_empty_sub": "Use /remember to save memories",
            "mem_add_title": "Add Memory",
            "mem_add_placeholder": "Enter something to remember",
            "mem_add_msg": "Saved as a memory referenced in all chats",
            "mem_delete_confirm": "Delete this memory?",
            "mem_count_fmt": "%d memories",
            "mem_count_unit": "items",
            "mem_hint": "Swipe left to delete",
            "mem_source_manual": "Manual",
            "mem_source_auto": "Auto",
        ],
        .spanish: [
            // General / shared
            "done": "Listo",
            "cancel": "Cancelar",
            "delete": "Eliminar",
            "save": "Guardar",
            "close": "Cerrar",
            "retry": "Reintentar",
            "back": "Atrás",
            "next": "Siguiente",
            "in_use": "En uso",
            "rename_session": "Renombrar",
            "rename_session_title": "Renombrar sesión",
            "rename_session_msg": "Ingresa un nuevo título para esta sesión",
            "session_title_placeholder": "Título de sesión",
            "state_generating": "Generando",
            "state_loading": "Cargando",
            "state_idle": "Listo",
            "state_not_loaded": "No cargado",
            "offline": "Sin conexión",
            "settings": "Configuración",
            "app_name": "Memoria",
            "reload": "Recargar",

            // ContentView / ModelLoadingView / ErrorView
            "model_loading": "Cargando modelo...",
            "first_download_wifi": "La primera descarga requiere Wi-Fi\n(~600MB)",
            "error_occurred": "Ocurrió un error",

            // SessionListView
            "welcome_heading": "Bienvenido a Memoria",
            "welcome_sub": "Tu asistente IA offline\nque te recuerda",
            "feature_offline": "Totalmente offline — datos en tu dispositivo",
            "feature_memory": "IA que aprende de tus conversaciones",
            "feature_multilang": "Japonés, inglés y español",
            "new_conversation": "Nueva conversación",
            "search_sessions": "Buscar sesiones...",
            "just_now": "ahora mismo",
            "yesterday": "Ayer",
            "min_ago_fmt": "hace %d min",
            "hour_ago_fmt": "hace %d h",
            "days_ago_fmt": "hace %d días",

            // ChatView
            "placeholder_message": "Escribe un mensaje...",
            "placeholder_command": "Escribe / para comandos",
            "placeholder_ask": "Pregúntame lo que quieras",
            "chat_start": "Inicia una conversación",
            "chat_empty_sub": "Funciona completamente offline\nEscribe / para comandos",
            "cmd_help_desc": "Lista de comandos",
            "cmd_english_desc": "Inglés nativo",
            "cmd_japanese_desc": "Japonés nativo",
            "cmd_spanish_desc": "Español nativo",
            "cmd_cal_desc": "Corregir auto-idioma",
            "cmd_grammar_desc": "Traducir y gramática",
            "cmd_remember_desc": "Guardar en memoria",
            "cmd_memory_desc": "Ver memorias",
            "cmd_clear_desc": "Nueva conversación",
            "voice_permission_title": "Se requiere permiso de micrófono",
            "voice_permission_msg": "Permite el acceso al micrófono y reconocimiento de voz para usar la entrada de voz.",
            "open_settings": "Abrir Ajustes",

            // SettingsView
            "section_appearance": "Apariencia",
            "section_model": "Modelo",
            "section_memory": "Memoria",
            "section_commands": "Comandos personalizados",
            "section_language": "Idioma",
            "section_about": "Acerca de",
            "follow_system_theme": "Seguir tema del sistema",
            "theme_label": "Tema",
            "color_palette": "Paleta de colores",
            "model_label": "Modelo",
            "memory_usage": "Uso de memoria",
            "change_model": "Cambiar modelo",
            "global_memory_label": "Memoria global",
            "session_count_label": "Sesiones",
            "clear_global_memory": "Borrar toda la memoria global",
            "delete_memory_title": "Borrar toda la memoria global",
            "delete_memory_msg": "Se eliminará toda la memoria global. Esta acción no se puede deshacer.",
            "app_language": "Idioma de la app",
            "version_label": "Versión",
            "inference_engine": "Motor de inferencia",
            "fully_offline_label": "Completamente offline",
            "disclaimer_label": "Aviso legal",
            "disclaimer_nav_title": "Aviso legal",
            "disclaimer_ai_title": "Sobre la precisión de la IA",
            "disclaimer_ai_body": "Las respuestas generadas por Memoria son inferencias del modelo de IA. No garantizamos exactitud, integridad ni puntualidad. Para decisiones importantes (médicas, legales, financieras), consulta a un profesional. El desarrollador no es responsable de los daños derivados del uso de las respuestas.",
            "disclaimer_model_title": "Atribución del modelo de IA",
            "disclaimer_model_body": "Esta app usa Gemma, un modelo de pesos abiertos desarrollado por Google DeepMind, bajo los Términos de uso de Google Gemma. La descarga del modelo requiere aceptar los Términos de servicio de HuggingFace.",
            "disclaimer_privacy_title": "Privacidad",
            "disclaimer_privacy_body": "Todos los datos de conversación y recuerdos de la IA se almacenan únicamente en tu iPhone. El micrófono se usa solo para entrada de voz y el audio se descarta inmediatamente tras la transcripción. No se envían datos a servidores externos (excepto la descarga inicial del modelo).",
            "disclaimer_oss_title": "Licencias de código abierto",
            "disclaimer_oss_body": "Esta app usa LLM.swift (MIT), GRDB.swift (MIT), llama.cpp (MIT) y Catppuccin (MIT). Los derechos de autor pertenecen a sus respectivos autores.",
            "last_updated": "Última actualización: Abril 2026",

            // ModelManagementView
            "model_mgmt_title": "Gestión de modelos",
            "local_models": "Modelos locales",
            "local_models_sub": "Offline · Privacidad protegida",
            "cloud_models": "Modelos en la nube",
            "cloud_models_sub": "Alto rendimiento · Requiere internet",
            "unload_btn": "Liberar",
            "switch_btn": "Cambiar",
            "download_btn": "Descargar",
            "use_model": "Usar",
            "badge_beta": "β Beta",
            "web_search_badge": "Búsqueda Web",
            "web_search_banner_title": "Búsqueda en Internet",
            "web_search_banner_body": "La IA en la nube buscará automáticamente en internet cuando necesite información actualizada. Los modelos de OpenAI no admiten búsqueda web actualmente.",
            "downloading": "Descargando...",
            "switching": "Cambiando...",
            "key_required": "Clave necesaria",
            "use_btn": "Usar",
            "api_key_not_set": "Clave API no configurada",
            "api_key_change": "Cambiar",
            "api_key_setup": "Configurar",
            "unload_confirm_title": "¿Liberar modelo de la memoria?",
            "unload_confirm_msg": "El modelo se liberará de la memoria. Se recargará la próxima vez.",
            "unload_confirm_action": "Liberar",
            "current_model_header": "Modelo actual",
            "not_selected": "No seleccionado",
            "offline_warning_title": "Sin conexión",
            "offline_warning_sub": "Los modelos en la nube requieren conexión a internet",
            "info_wifi": "Los modelos locales requieren una descarga única por Wi-Fi",
            "info_keychain": "Las claves API se cifran y almacenan en el Keychain del iPhone",
            "device_memory": "Memoria del dispositivo: %@ GB",
            "mem_optimal": "Recomendado",
            "mem_usable": "Usable",
            "mem_tight": "Precaución",
            "mem_tight_warning": "Puede volverse inestable por memoria insuficiente. Funciona, pero úsalo bajo tu responsabilidad.",

            // QuickModelPickerView
            "quick_model_title": "Cambiar modelo",
            "current_model_active": "Modelo activo",
            "local_models_short_sub": "Offline · Privacidad",
            "api_key_set": "Clave API configurada",
            "setup_api_key": "Configurar",
            "api_key_needed": "Clave API necesaria",
            "full_settings_label": "Configuración avanzada y claves API",
            "full_settings_sub": "Descarga modelos y gestiona claves API",

            // ChatView UX improvements
            "new_session_confirm_title": "¿Iniciar nueva conversación?",
            "new_session_confirm_msg": "Tu conversación actual se guardará",
            "new_session_confirm_btn": "Iniciar nueva conversación",
            "api_key_required_title": "Se requiere clave API",
            "api_key_required_msg": "Se necesita una clave API para usar este modelo. ¿Configurarla ahora?",
            "api_key_set_now": "Configurar ahora",
            "recording_label": "Escuchando...",
            "tap_to_stop": "Toca para detener",
            "swipe_hint": "← Desliza para eliminar o renombrar",
            "offline_cloud_banner": "Sin conexión — IA en la nube no disponible",
            "badge_local": "Local",
            "badge_cloud": "Nube",
            "api_key_setup_nav_title": "Configurar clave API",
            "api_key_keychain_note": "Tu clave API se cifra y almacena en el Keychain del iPhone",
            "api_key_already_set": "Configurado",

            // OnboardingView
            "onboarding_welcome": "Bienvenido a Memoria",
            "onboarding_subtitle": "Un asistente IA privado\nque te recuerda",
            "badge_offline": "Completamente offline",
            "badge_memory": "Memoria",
            "badge_voice": "Entrada de voz",
            "features_title": "Características",
            "onb_feature1_title": "Funciona solo en tu iPhone",
            "onb_feature1_desc": "Todo el procesamiento de IA ocurre en el dispositivo. Tus datos nunca salen del iPhone.",
            "onb_feature2_title": "Recuerda conversaciones",
            "onb_feature2_desc": "Resume y recuerda conversaciones entre sesiones. Un asistente personal con contexto.",
            "onb_feature3_title": "Powered by Gemma (Google DeepMind)",
            "onb_feature3_desc": "Usa los últimos LLMs de código abierto. Gemma 4 disponible en iPhone 16 y posterior.",
            "onb_disclaimer_title": "Antes de comenzar",
            "onb_disclaimer1_title": "⚠️ Sobre la precisión de la IA",
            "onb_disclaimer1_body": "Las respuestas generadas por Memoria son inferencias del modelo de IA. No garantizamos exactitud, integridad ni puntualidad. Para decisiones críticas (médicas, legales, financieras), consulta a un profesional.",
            "onb_disclaimer2_title": "🤖 Sobre el modelo de IA",
            "onb_disclaimer2_body": "Esta app ejecuta localmente Gemma (un modelo abierto de Google DeepMind). El modelo se descarga de HuggingFace. El uso requiere aceptar los Términos de uso de Google Gemma.",
            "onb_disclaimer3_title": "🔒 Privacidad",
            "onb_disclaimer3_body": "Los datos de conversación se almacenan únicamente en tu iPhone. El micrófono se usa solo para entrada de voz; no se guardan ni transmiten grabaciones.",
            "onb_agreement": "He leído y entendido los avisos anteriores y acepto usar Memoria bajo mi propia responsabilidad.",
            "onb_agree_btn": "Aceptar e iniciar Memoria",

            // UserCommandManagementView
            "cmd_manage_title": "Comandos personalizados",
            "cmd_manage_empty": "Aún no hay comandos",
            "cmd_manage_empty_sub": "Toca + para agregar tu primer comando",
            "cmd_add_title": "Agregar comando",
            "cmd_field_name": "Nombre del comando (ej: resumir)",
            "cmd_field_desc": "Descripción (ej: Resumir texto)",
            "cmd_field_template": "Plantilla de prompt",
            "cmd_template_hint": "{input} será reemplazado por el texto después del comando\nEjemplo: Resume lo siguiente en 3 líneas: {input}",
            "cmd_name_label": "Nombre",
            "cmd_desc_label": "Descripción",
            "cmd_template_label": "Plantilla",
            "cmd_usage_label": "Cómo usar",
            "cmd_usage_example": "/comando [texto a enviar]",
            "cmd_delete_confirm": "¿Eliminar este comando?",
            "cmd_settings_row": "Gestionar comandos",
            "cmd_settings_sub": "Agrega y elimina tus propios comandos del chat",
            "cmd_count_fmt": "%d comandos",
            "cmd_name_invalid": "El nombre contiene caracteres no válidos",
            "cmd_name_duplicate": "Ya existe un comando con ese nombre",
            "cmd_add_success": "Comando agregado",
            "cmd_edit_title": "Editar comando",
            "cmd_name_readonly": "Solo lectura",
            // GlobalMemoryManagementView
            "mem_manage_title": "Memoria global",
            "mem_empty_title": "Memoria vacía",
            "mem_empty_sub": "Usa /remember para guardar recuerdos",
            "mem_add_title": "Agregar memoria",
            "mem_add_placeholder": "Escribe algo para recordar",
            "mem_add_msg": "Se guardará como memoria para todos los chats",
            "mem_delete_confirm": "¿Eliminar esta memoria?",
            "mem_count_fmt": "%d memorias",
            "mem_count_unit": "ítems",
            "mem_hint": "Desliza para eliminar",
            "mem_source_manual": "Manual",
            "mem_source_auto": "Auto",
        ],
    ]
}
